# Generated by Django 5.2.1 on 2025-05-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together=set(),
        ),
    ]
