# Generated by Django 5.2.1 on 2025-05-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_testresult_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='allowed_groups',
            field=models.TextField(blank=True, help_text='Список групп через запятую', verbose_name='Доступные группы'),
        ),
    ]
